#! /bin/sh

TEST=$(pwd)/bin/test/PROJET_PR6
PROD=$(pwd)/bin/production/PROJET_PR6

DIR=$TEST:$PROD
LIBS=lib/hamcrest-core-1.3.jar:lib/junit-4.11.jar

[ ! -d bin/production ] && echo "No compiled source." && exit 1


get_all_files() {
    echo $(for i in $(find $TEST/$1/*); do \
        local tmp=$(basename $i)
        echo $1.${tmp%%.class}
        done;
    )
}

FORMATS_FILES=$(get_all_files formats)
DATA_FILES=$(get_all_files data)

echo "\n### FORMATS\n\n"
java -classpath "$DIR:$LIBS" org.junit.runner.JUnitCore $FORMATS_FILES

echo "\n### DATA\n\n"
java -classpath "$DIR:$LIBS" org.junit.runner.JUnitCore $DATA_FILES
